name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      # Add automerge and awesome labels if tests pass
      - name: Add labels if tests pass
        if: success()
        uses: actions/ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use your PAT secret here
          labels: 'automerge,awesome'
