name: CI

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
  
      - name: Check out the repository
        uses: actions/checkout@v2
  
      - name: Add 'awesome' label to all PRs
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          labels: 'awesome'
