name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

      # Automerge if tests pass
      - name: Automerge
        if: success() && github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          git config --global user.name "VedantKhairnar"
          git config --global user.email "khairnarvc@rknec.edu"
          git fetch origin main
          git checkout main
          git merge --no-ff --no-edit FETCH_HEAD
          git push origin main
          
      # Automatically merge the pull request
      - name: Merge pull request
        if: success() && github.event_name == 'pull_request'
        uses: pullreminders/automerge-action@v2
        with:
          github_token: ${{ secrets.TOKEN }}
